name: rocket
description: A client for Reddit, built with Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-417.3.beta <4.0.0'

dependencies:
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  riverpod_annotation: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.1
  commitlint_cli: ^0.4.0
  custom_lint: ^0.3.4
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  http_mock_adapter: ^0.4.2
  husky: ^0.1.6
  json_serializable: ^6.6.1
  mockito: ^5.4.0
  riverpod_generator: ^2.2.1
  riverpod_lint: ^1.3.1

flutter:
  uses-material-design: true
