name: rocket
description: A client for Reddit, built with Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.4
  commitlint_cli: ^0.4.1
  custom_lint: ^0.4.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  http_mock_adapter: ^0.4.4
  husky: ^0.1.6
  json_serializable: ^6.7.0
  mockito: ^5.4.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2

flutter:
  uses-material-design: true
